---
- name: This playbook sets up NZ OSM infrastructure with Vagrant
  hosts: vagrant
  become: true
  become_method: sudo
  become_user: root

  vars_files:
    - vars/default.yml

  roles:
    - base
    - locale
    - postgresql
    - nginx
    - mapserver
    - imposm
    - osm
    - basemaps

- name: This playbook sets up NZOSS GIS Live DVD infrastructure
  gather_facts: no
  hosts: catalyst
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - vars/default.yml

  roles:
    - base
    - locale
    - postgresql
    - nginx
    - mapserver
    - imposm
    - osm
    - basemaps
