---
- name: This playbook sets up NZ OSM infrastructure with Vagrant
  hosts: vagrant
  become: true

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - postgresql
    - nginx
    - mapserver
    - imposm
    - osm
    - basemaps

- name: This playbook sets up NZOSS GIS Live DVD infrastructure
  hosts: catalyst
  become: true

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - postgresql
    - nginx
    - mapserver
    - imposm
    - osm
    - basemaps
