---
- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - protobuf-compiler
    - libprotobuf-dev
    - libtokyocabinet-dev
    - python-psycopg2
    - libgeos-c1
    - python-pip
    - unzip

  tags:
    - imposm

- pip: name=imposm

- file: path=/var/imposm/ state=directory mode=0755

- name: create database with imposm
  become: yes
  shell: imposm-psqldb | awk '{ if ($0 != "createlang plpgsql osm") print }' | sed 's/\/path\/to\/pg_hba.conf/\/etc\/postgresql\/9.4\/main\/pg_hba.conf/' | sed 's/\/path\/to\//\/usr\/share\/postgresql\/9.4\/contrib\/postgis-2.1\//' > /var/imposm/create-db.sh && sudo -u postgres /bin/bash /var/imposm/create-db.sh
  args:
    creates: /var/imposm/create-db.sh
  notify: restart postgresql
