---
- name: Download imposm3 (go binary) and unarchive it into /opt/imposm
  get_url:
    url: https://github.com/omniscale/imposm3/releases/download/v0.10.0/imposm-0.10.0-linux-x86-64.tar.gz
    dest: /opt/imposm3.tar.gz
  tags:
    - imposm

- name: Create path for imposm3
  file: path=/opt/imposm3/ state=directory owner=root group=root mode=0755
  tags:
    - imposm

- name: Unarchive imposm3
  unarchive:
    src: /opt/imposm3.tar.gz
    dest: /opt/
    remote_src: yes
    list_files: yes
  register: archive_contents
  tags:
    - imposm

- name: Move imposm3 directory
  shell: mv /opt/{{ archive_contents.files[0] }} /opt/imposm3
  args:
    creates: /opt/imposm3

- name: Create imposm database
  become_user: postgres
  postgresql_db:
    name: osm

- name: Connect to osm database and set user's password with no expire date
  become_user: postgres
  postgresql_user:
    db: osm
    name: osm
    password: osm
    priv: "ALL"
    expires: infinity

- name: Adds postgis extension to the database osm
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: osm
