postgresql_version: "9.6"
postgresql_package_version: "9.6.*-1.pgdg20.04+1"

logstash_version: "1.5"

server_name: 192.168.100.100

locale: en_US.UTF-8

ansible_python_interpreter: "/usr/bin/python3"
